name: Ruby on Rails & PostgreSQL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6.5

    - name: Install dependencies
      run: bundle install

    - name: Set up PostgreSQL
      run: |
        sudo apt-get install postgresql libpq-dev
        sudo service postgresql start
        sudo -u postgres createuser --superuser "$USER"

    - name: Install and Compile Javascript with webpacker 
      run: |
        yarn install --check-files
        bundle exec rails webpacker:install
        bundle exec rails webpacker:compile

    - name: Set up Database
      run: bundle exec rails db:migrate:reset
      env:
        RAILS_ENV: test

    - name: Run tests
      run: bundle exec rake
        - name: Upload
      uses: actions/upload-artifact@v2 # 利用するアクションを指定
      if: failure() # 失敗したときだけ実行
      with:
        name: my-uploads
        path: tmp/screenshots/ # uploadするパス（Rails rootからの相対パス）
